version: '3.9'

services:
  websocket-app:
    image: websocket-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
        - SPRING_APPLICATION_JSON={"spring.kafka.consumer.bootstrap-servers":"kafka1:29092","spring.kafka.consumer.group-id":"place_holder","spring.kafka.consumer.key-deserializer":"org.apache.kafka.common.serialization.StringDeserializer","spring.kafka.consumer.value-deserializer":"org.apache.kafka.common.serialization.StringDeserializer"}
    networks:
      - hadoop_hadoop

networks:
  hadoop_hadoop:
    external: true
